# prl_convert
# Autogenerated from man page /usr/share/man/man8/prl_convert.8
# using Type1
complete -c prl_convert -l dst --description 'Set the destination directory.'
complete -c prl_convert -s r -l reg --description 'Register the resulting virtual machine on the P… [See Man Page]'
complete -c prl_convert -l os-files --description 'Set the path to the operating system installation files.'
complete -c prl_convert -l vbox-home --description 'Specify the path to the directory storing virtu… [See Man Page]'
complete -c prl_convert -l err-code --description 'Show error codes instead of text messages.'
complete -c prl_convert -l allow-no-os --description 'Allow to convert data disks or disks whose oper… [See Man Page]'
complete -c prl_convert -l no-reconfig --description 'Skip the reconfiguration step when converting a virtual disk.'
complete -c prl_convert -l no-src-check --description 'Do not check the source virtual disk state.'
complete -c prl_convert -l no-hibernate-check --description 'Do not check whether the guest operating system is hibernated.'

