# prl_disk_tool
# Autogenerated from man page /usr/share/man/man8/prl_disk_tool.8
# using Deroffing man parser
complete -c prl_disk_tool -l hdd --description 'This option is mandatory and specifies the full… [See Man Page]'
complete -c prl_disk_tool -l comm --description 'This parameter is not currently used. SS Disk resizing:.'
complete -c prl_disk_tool -l size --description 'Set the virtual hard disk size in MB (by default) or GB.'
complete -c prl_disk_tool -l resize_partition --description 'Resize the last partition and its file system w… [See Man Page]'
complete -c prl_disk_tool -l force --description 'Forcibly drop the suspended state before resizing the disk.'
complete -c prl_disk_tool -l split --description 'Split the virtual hard disk by 2 GB.'
complete -c prl_disk_tool -s i -l info --description 'Display the capacity of the specified virtual d… [See Man Page]'
complete -c prl_disk_tool -l units --description 'Used with the --info option, shows the disk siz… [See Man Page]'
complete -c prl_disk_tool -l buildmap --description 'If this option is specified, the utility scans … [See Man Page]'
complete -c prl_disk_tool -l exclude-pagefile --description 'If this option is specified, the utility will r… [See Man Page]'
complete -c prl_disk_tool -l boot --description 'Specifies the full path to the Parallels boot driver.'
complete -c prl_disk_tool -l para --description 'Specifies the full path to the Parallels paravi… [See Man Page]'
complete -c prl_disk_tool -l toolsag --description 'Specifies the full path to the PTIAgent.'
complete -c prl_disk_tool -l expanding --description 'reduce the size of a plain disk to the actual a… [See Man Page]'
complete -c prl_disk_tool -l plain --description 'convert an expandable disk to a disk of fixed c… [See Man Page]'
complete -c prl_disk_tool -l merge --description 'merge all parts of a split disk into one file. SS Encryption.'
complete -c prl_disk_tool -l help --description 'Print usage.'

